name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  quick-checks-unit-tests:
    name: Forge quick checks and unit tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check code formatting
        run: forge fmt --check
      
      - name: Install submodules
        run: forge install

      - name: Check gas snapshots
        run: forge snapshot # --check TODO get /master gas snapshot up-to-date
        env:
          RPC_URL: https://eth-mainnet.alchemyapi.io/v2/SzNcOCE77s6nmGIal7MxtuzF--q2HZgx

      - name: Run tests
        run: forge test --optimize --no-match-contract integration
        env:
          RPC_URL: https://eth-mainnet.alchemyapi.io/v2/SzNcOCE77s6nmGIal7MxtuzF--q2HZgx

      - name: Coverage
        run: |
          forge coverage --report lcov
        id: coverage
        env:
          RPC_URL: https://eth-mainnet.alchemyapi.io/v2/SzNcOCE77s6nmGIal7MxtuzF--q2HZgx

      - uses: codecov/codecov-action@v3 # TODO grant access and add token

  # integration-tests:
  #   name: Forge integration tests
  #   runs-on: ubuntu-latest
  #   steps:

  #     - uses: actions/checkout@v3

  #     - name: Install Foundry
  #       uses: onbjerg/foundry-toolchain@v1
  #       with:
  #         version: nightly
      
  #     - name: Install submodules
  #       run: forge install

  #     - name: Run tests
  #       run: forge test --optimize --match-contract integration
  #       env:
  #         RPC_URL: https://eth-mainnet.alchemyapi.io/v2/SzNcOCE77s6nmGIal7MxtuzF--q2HZgx

  static-analysis:
    name: Slither static analysis
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        with:
          target: "src/"
          slither-config: slither.config.json
          sarif: results.sarif
          fail-on: none



      # - uses: actions/setup-node@v2

      # - name: Install dev dependencies
      #   run: npm install

      # - name: Set up python
      #   id: setup-python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.9

      # - name: Install Poetry
      #   uses: snok/install-poetry@v1

      # - name: Load cached venv
      #   id: cached-poetry-dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: .venv
      #     key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      # - name: Install dependencies
      #   if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      #   run: poetry install --no-interaction --no-root

      # - name: Install library
      #   run: poetry install --no-interaction

      # - name: Run lint check
      #   run: npm run lint:check




      # Too slow to run regularly
      #- name: Run audit
      #  run: poetry run slither --solc-remaps @openzeppelin=lib/openzeppelin-contracts --solc-args optimize src/


  # run-ci:
  #   name: Forge build and tests